[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "benfleis-beancount-importers"
version = "0.1.0"
authors = []
requires-python = ">=3.7"
license = {text = "BSD-3-Clause"}

[tool.setuptools]
